import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "../globals.css";
import Navbar from "@/components/navbar/Navbar";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { setRequestLocale } from "next-intl/server";
import Footer from "@/components/footer/Footer";
import SessionProvider from "@/lib/SessionProvider";
import QueryClientProvider from "@/lib/QueryClientProvider";

const gravesend = localFont({
  variable: "--font-gravesend",
  src: [
    { path: '../../../public/fonts/gravesend-sans-family/gravesend-sans-medium.ttf', weight: "400", style: "normal" },
    { path: '../../../public/fonts/gravesend-sans-family/gravesend-sans-bold.ttf', weight: "700", style: "normal" }
  ]
})


const gilory = localFont({
  variable: "--font-gilory",
  src: [
    // Use filesystem-relative paths so the compiler can resolve these files
    { path: "../../../public/fonts/gilroy/Gilroy-Regular.ttf", weight: "400", style: "normal" },
    { path: "../../../public/fonts/gilroy/Gilroy-Medium.ttf", weight: "500", style: "normal" },
    { path: "../../../public/fonts/gilroy/Gilroy-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "../../../public/fonts/gilroy/Gilroy-Bold.ttf", weight: "700", style: "normal" },
    // { path: "../../../public/fonts/Sen/static/Sen-Medium.ttf", weight: "500", style: "normal" },
    // { path: "../../../public/fonts/Sen/static/Sen-SemiBold.ttf", weight: "600", style: "normal" },
    // { path: "../../../public/fonts/Sen/static/Sen-Bold.ttf", weight: "700", style: "normal" },
    // { path: "../../../public/fonts/Sen/static/Sen-ExtraBold.ttf", weight: "800", style: "normal" },
    // // Fallback to variable file if present
    // { path: "../../../public/fonts/Sen/Sen-VariableFont_wght.ttf", weight: "100 900", style: "normal" },
  ],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};
export default async function RootLayout({
  children,
  params
}: Props) {

  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  setRequestLocale(locale);

  return (
    <html lang={locale}   >
      <body
        className={`dark  ${gravesend.variable}  ${gilory.variable} ${geistMono.variable}  antialiased `}
      >
        <SessionProvider>
          <QueryClientProvider>

            <NextIntlClientProvider >
              {children}
            </NextIntlClientProvider>
          </QueryClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
